"use client";

import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

import { Inter } from "next/font/google";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { cn } from "@/lib/utils";
import { usePomodoroStore } from "@/lib/store";
import { useEffect } from "react";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

import "./globals.css";
import { twMerge } from "tailwind-merge";
import clsx from "clsx";
// export const metadata: Metadata = {
// 	title: "Pomodoro App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const hydrate = usePomodoroStore((state) => state.hydrate);
	const pathname = usePathname();

	// Hydrate the store from local storage on initial load
	useEffect(() => {
		hydrate();
	}, [hydrate]);

	return (
		<html lang="en">
			<head>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0"
				/>
				<title>Pomodoro App</title>
			</head>
			<body className={cn(inter.className, "min-h-screen flex flex-col")}>
				<header className="border-b bg-background p-4">
					<nav className="container flex  items-center justify-between border-border ">
						<h1 className="text-2xl font-bold">Pomodoro App</h1>
						<div className="flex space-x-4">
							<Link href="/">
								<span
									className={twMerge(
										clsx(
											"text-muted-foreground hover:text-primary ",
											pathname === "/" &&
												"text-primary font-semibold"
										)
									)}
								>
									Timer
								</span>
							</Link>
							<Link href="/done-tasks">
								<span
									className={cn(
										"text-muted-foreground hover:text-primary",
										pathname === "/done-tasks" &&
											"text-primary font-semibold"
									)}
								>
									Done Tasks
								</span>
							</Link>
							<Link href="/settings">
								<span
									className={cn(
										"text-muted-foreground hover:text-primary",
										pathname === "/settings" &&
											"text-primary font-semibold"
									)}
								>
									Settings
								</span>
							</Link>
						</div>
					</nav>
				</header>
				<main className="flex-grow container mx-auto p-4 flex flex-col items-center justify-center">
					{children}
				</main>
				<Toaster />
			</body>
		</html>
	);
}
